services:
  # 서비스 image를 어떤 방식으로 Container에 동작시킬지에 대한 서비스 단락
  webserver: 
    image: nodeserver:v2
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - mynet1
      - mynet2
  
  nginx:
    image: nginx:v2
    ports:
      - 80:80
    networks:
      - mynet1
    restart: always

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - mynet2
    volumes:
      - ./vol:/var/lib/postgresql/data

networks:
  mynet1:
  mynet2: