services:
  # 서비스 image를 어떤 방식으로 Container에 동작시킬지에 대한 서비스 단락
  server-container: 
    image: nodeserver:v1
    ports:
      - 8080:8080
    depends_on:
      - db
  
  nginx:
    image: nginx:v1
    ports:
      - 80:80

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}